MESSAGES = {
    "tr": {
        "lang_selection": "👋 <b>Merhaba {first_name}! / Hello {first_name}!</b>\n\n🤖 <b>GagaraGogo Userbot Kurulum Asistanı</b>\nLütfen devam etmek istediğiniz dili seçin:\nPlease select your preferred language:",
        "start_en_btn": "🇬🇧 English",
        "start_tr_btn": "🇹🇷 Türkçe",
        "start_welcome": "👋 <b>Merhaba {first_name}!</b>\n\n🤖 <b>GagaraGogo Userbot Otomatik Kurulum Asistanı</b>'na hoş geldiniz.\n\nBu asistan ile hiçbir kodlama yapmadan:\n1️⃣ Render hesabınıza bağlanır,\n2️⃣ <code>my.telegram.org</code> üzerinden API ID ve HASH alınır,\n3️⃣ String Session üretilir,\n4️⃣ <code>@BotFather</code> üzerinden otomatik yardımcı bot açılır,\n5️⃣ Botunuz Render'a kurulur ve 7/24 Uptime linkiniz teslim edilir!\n\n🔒 <b>Güvenlik & Sıfır Depolama:</b>\n<i>Girdiğiniz telefon, şifre ve kodlar sunucularımızda ASLA depolanmaz.</i>\n\n⏳ <b>Otomatik Gizlilik Koruması:</b>\n• Başarılı kurulumlarda: <b>5 dakika sonra</b>\n• Yarım kalan veya iptal edilen işlemlerde: <b>30 dakika sonra</b>\nbu sohbetteki tüm mesajlar güvenliğiniz için otomatik olarak tamamen silinir!\n\n⚠️ <b>Sorumluluk Reddi (Disclaimer):</b>\n<i>Userbot kullanımı Telegram şartları gereği hesabınız için risk taşıyabilir. Hesabınızdan ve yaptığınız işlemlerden bizzat kendiniz sorumlusunuz; geliştiriciler hiçbir sorumluluk kabul etmez. Kuruluma başlayarak bu şartları peşinen kabul etmiş sayılırsınız.</i>\n\n📁 <b>Açık Kaynak Kodları:</b>\n<a href='https://github.com/chaolcam/gagaragogo-kurulum-bot'>github.com/chaolcam/gagaragogo-kurulum-bot</a>",
        "btn_start_setup": "🚀 Kuruluma Başla",
        "btn_remove_bot": "🗑️ Botumu Hesaptan Kaldır",
        "btn_lang_change": "🌐 Dil / Language (TR / EN)",
        "btn_privacy": "ℹ️ Güvenlik & Gizlilik",
        "btn_github": "📁 Kaynak Kodları (GitHub)",
        "render_step_1_cap": "📸 <b>Render - 1. Adım:</b>\nSağ üstteki profil simgenize (daire içindeki alana) tıklayın, ardından açılan menüden okla gösterilen <b>Account settings</b> kısmına basın.",
        "render_step_2_cap": "📸 <b>Render - 2. Adım:</b>\nSol menüden <b>API Keys</b> sekmesine gelin ve <b>Create API Key</b> butonuna basın. Açılan kutuda bir isim verip onaylayın. Size verilen <code>rnd_...</code> ile başlayan API anahtarınızı kopyalayın.",
        "step_1_render_key": "🌐 <b>Adım 1: Render API Anahtarı</b>\n\nBotunuzun 7/24 ücretsiz çalışacağı sunucuyu bağlamak için Render API anahtarınız gereklidir:\n\n1️⃣ <a href='https://dashboard.render.com/'>dashboard.render.com</a> adresine gidip hesabınıza giriş yapın.\n2️⃣ Yukarıdaki resimli adımlarda gösterildiği gibi <code>rnd_...</code> anahtarınızı oluşturun.\n3️⃣ Oluşturulan <code>rnd_...</code> anahtarını kopyalayıp buraya gönderin:\n\n❌ <i>İptal etmek için /cancel yazabilirsiniz.</i>",
        "remove_bot_msg": "🗑️ <b>GagaraGogo Userbot'u Kaldırma</b>\n\nLütfen Render hesabınızdaki servisi silmek için **Render API Anahtarınızı** (`rnd_...`) mesaj olarak gönderin:",
        "privacy_info": "🛡️ <b>GagaraGogo Güvenlik & Gizlilik İlkeleri</b>\n\n• <b>%100 Açık Kaynak:</b>\nTüm kurulum ve deploy kaynak kodları GitHub üzerinde açıktır:\n👉 <a href='https://github.com/chaolcam/gagaragogo-kurulum-bot'>github.com/chaolcam/gagaragogo-kurulum-bot</a>\n\n• <b>Sıfır Depolama (Zero-Persistence):</b>\nGirdiğiniz API anahtarları, telefon numarası veya onay kodları sunucuda <b>asla</b> veritabanına veya diske kaydedilmez. Sadece o anlık RAM hafızada işlenir ve bittiğinde yok edilir.\n\n• <b>Otomatik Sohbet Temizleme:</b>\n1️⃣ Başarılı kurulumlarda: <b>5 dakika sonra</b>\n2️⃣ Yarım kalan veya iptal edilen işlemlerde: <b>30 dakika sonra</b>\nsohbetteki tüm hassas mesajlar güvenliğiniz için otomatik olarak tamamen silinir.\n\n• <b>⚠️ Sorumluluk Reddi Beyanı (Disclaimer):</b>\nUserbot kullanımı üçüncü parti bir yazılımdır ve Telegram hesabınız sınırlandırılabilir veya yasaklanabilir. Bu açık kaynaklı bir projedir; hesabınızdan ve paylaşımlarınızdan <b>bizzat kendiniz sorumlusunuz</b>. GagaraGogo geliştiricileri ve yöneticileri hiçbir sorumluluk kabul etmemektedir.",
        "btn_back_main": "⬅️ Ana Menüye Dön",
        "wait_botfather": "⏳ <i>@BotFather ile konuşuluyor, yardımcı botunuz ve inline menü açılıyor...</i>",
        "auto_bot_error": "⚠️ Otomatik bot açılırken bir sorun oluştu: `{e}`\n\nLütfen @BotFather'dan aldığınız bir Bot Token'ı elle mesaj olarak gönderin:",
        "manual_bot_msg": "✏️ Lütfen @BotFather'dan aldığınız bot tokenınızı yapıştırın:\nÖrnek: `1234567890:ABCdef...`",
        "official_api_selected": "✅ <b>Telegram Resmi Android API Seçildi!</b>\n• API ID: <code>2040</code>\n• API HASH: <code>b18441a1ff607e10a989891a5462e627</code>\n\n⏳ <i>Giriş onay kodunuz (SMS/Telegram) gönderiliyor...</i>",
        "retry_code": "⏳ <i>Giriş kodu tekrar isteniyor...</i>",
        "start_command_required": "Lütfen kuruluma başlamak için /start komutunu kullanın.",
        "invalid_render_key": "⚠️ Render API anahtarları `rnd_` ile başlar. Lütfen doğru anahtarı girdiğinizden emin olun:",
        "verifying_render_key": "⏳ <i>Render API anahtarı doğrulanıyor...</i>",
        "render_key_success": "✅ <b>Render API Anahtarı Doğrulandı!</b>\n\n📱 <b>Adım 2: Telegram Telefon Numarası</b>\n\nAşağıdaki butona basarak telefon numaranızı paylaşın veya uluslararası formatta yazın:\nÖrnek: `+905551234567`\n\n🔒 <i>Numaranız sadece anlık Telegram doğrulama kodu istemek için kullanılır, ASLA kaydedilmez.</i>",
        "render_key_error": "❌ <b>Hata:</b> {e}\n\nLütfen Render API anahtarınızı kontrol edip tekrar gönderin:",
        "btn_share_phone": "📱 Telefon Numaramı Paylaş",
        "invalid_phone": "❌ Geçersiz telefon numarası. Lütfen örn: `+905551234567` şeklinde yazın:",
        "contacting_my_tg": "⏳ <b>my.telegram.org</b> ile iletişim kuruluyor...\nNumara: <code>{phone}</code>",
        "tg_code_sent": "📨 <b>Telegram Doğrulama Kodu Gönderildi!</b>\n\nTelegram resmi bildirimlerinden gelen web giriş kodunu buraya gönderin.\n\n⚠️ <b>ÖNEMLİ FORMAT UYARISI:</b>\nTelegram gelen kodların otomatik doğrulanmasını engellediği için lütfen kodu <b>aralarında boşluk bırakarak</b> yazın:\n👉 <i>Örnek: Kod <code>93964</code> ise buraya <code>9 3 9 6 4</code> veya <code>9.3.9.6.4</code> şeklinde yazın.</i>\n\n❌ <i>İptal etmek için /cancel yazabilirsiniz.</i>",
        "mytg_unreachable": "⚠️ <b>my.telegram.org Sitesine Ulaşılamadı</b>\n\nTelegram sunucularındaki yoğunluk nedeniyle web sitesi yanıt vermedi.\nAncak endişelenmeyin! Telegram'ın resmi Android uygulamasının hazır ve lisanslı genel API anahtarlarını kullanarak devam edebilirsiniz:",
        "btn_use_official_api": "✅ Resmi Android API ile Devam Et",
        "btn_cancel": "❌ İptal Et",
        "logging_in_mytg": "⏳ <i>my.telegram.org girişi yapılıyor ve API anahtarları alınıyor...</i>",
        "api_retrieved": "✅ <b>API Bilgileriniz Başarıyla Alındı!</b>\n\n• <b>API ID:</b> <code>{api_id}</code>\n• <b>API HASH:</b> <code>{api_hash}</code>\n\n⏳ <i>Şimdi String Session üretmek için Telegram uygulamanıza giriş kodu gönderiliyor...</i>",
        "generating_session": "⏳ <i>Oturum açılıyor ve String Session üretiliyor...</i>",
        "session_code_sent": "📱 <b>Telegram Giriş Kodunuz Gönderildi!</b>\n\nLütfen Telegram uygulamanıza gelen giriş kodunu buraya gönderin.\n\n⚠️ <b>ÖNEMLİ:</b> Kodu <b>aralarında boşluk bırakarak</b> yazın:\n👉 <i>Örnek: <code>1 2 3 4 5</code></i>",
        "session_code_error": "❌ Kod gönderilirken hata oluştu: `{e}`\n\nLütfen tekrar deneyin:",
        "login_error": "❌ <b>Giriş Hatası:</b> {e}\n\nLütfen kodu doğru girdiğinizden emin olun (Örn: <code>9 3 9 6 4</code>) veya /start ile baştan deneyin.",
        "verifying_2fa": "⏳ <i>2FA şifresi doğrulanıyor...</i>",
        "need_2fa": "🔐 <b>İki Adımlı Doğrulama (2FA) Şifresi Gerekli</b>\n\nHesabınızda 2FA şifresi aktif. Lütfen Telegram bulut şifrenizi mesaj olarak gönderin:\n\n🔒 <i>Şifreniz hiçbir yere kaydedilmez, anlık doğrulamadan sonra hafızadan tamamen silinir.</i>",
        "2fa_error": "❌ <b>Hata:</b> {e}\n\nLütfen şifrenizi tekrar deneyin veya /cancel yazın.",
        "session_success": "🔐 <b>String Session Başarıyla Üretildi!</b>\n\n🤖 <b>Son Adım: Yardımcı Bot Kurulumu</b>\n\nGagaraGogo Userbot'un inline buton menüleri ve ayar paneli için bir yardımcı bota ihtiyacı vardır.\n\n• <b>Otomatik Oluştur:</b> Botunuz @BotFather ile konuşup saniyeler içinde yeni bot açar ve inline modunu ayarlar.\n• <b>Manuel Giriş:</b> Daha önceden aldığınız bir Bot Token'ı kendiniz yapıştırabilirsiniz.\n\nYardımcı botun otomatik açılmasını veya manuel girilmesini sorar.",
        "btn_auto_bot": "🤖 Otomatik Bot Aç (Önerilen)",
        "btn_manual_bot": "✏️ Bot Token'ı Kendim Gireceğim",
        "invalid_bot_token": "❌ Geçersiz bot token formatı! Örn: `1234567890:ABCdef...`",
        "searching_render_service": "⏳ <i>Render hesabınızdaki 'gagaragogo-userbot' servisi aranıyor ve siliniyor...</i>",
        "no_render_service": "ℹ️ Render hesabınızda aktif bir 'gagaragogo-userbot' servisi bulunamadı.\nYeniden başlamak veya botu kaldırmak isterseniz aşağıdaki butonları kullanabilirsiniz:",
        "remove_success": "✅ <b>GagaraGogo Userbot Render servisiniz başarıyla silindi!</b>\n\nTüm sunucu işlemleri ve kaynaklar hesabınızdan tamamen kaldırılmıştır.\nBotu kaldırmak veya yeniden işlem yapmak isterseniz aşağıdaki butonları kullanabilirsiniz:",
        "remove_error": "❌ Kaldırma Hatası: {e}\nBotu kaldırmak veya yeniden işlem yapmak isterseniz aşağıdaki butonları kullanabilirsiniz:",
        "btn_restart_setup": "🚀 Yeniden Kuruluma Başla",
        "cancel_full": "❌ <b>İşlem iptal edildi.</b>\n\nTüm geçici veriler hafızadan silindi.\n⏳ <i>Güvenliğiniz için bu sohbet 30 dakika içinde otomatik olarak temizlenecektir.</i>",
        "deploy_starting": "🚀 <b>GagaraGogo Kurulumu Başlatılıyor...</b>\n\nRender hesabınızda <code>gagaragogo-userbot</code> servisi oluşturuluyor ve değişkenler yükleniyor...",
        "deploy_success": "🎉 <b>TEBRİKLER! GAGARAGOGO USERBOT KURULDU!</b>\n\n🚀 <b>Render Web Servisiniz Başlatıldı:</b>\n• <b>Servis Adı:</b> <code>{name}</code>\n• <b>Panel Linki:</b> <a href='{dashboard_url}'>Render Dashboard</a>\n\n🔗 <b>Size Özel Canlı Web Adresiniz:</b>\n👉 <code>{app_live_url}</code>\n\n🔑 <b>Hesap Anahtarlarınız:</b>\n<i>(Kurulum ve erişim bilgileriniz Telegram Kayıtlı Mesajlar sohbetinizde saklanmaktadır.)</i>\n\n<i>Güvenliğiniz için bu sohbetteki tüm kurulum mesajları ve anahtarlar <b>5 dakika sonra otomatik olarak silinecektir</b>. Kurulum bilgileriniz Kayıtlı Mesajlar (Saved Messages) kutunuza güvenle yedeklenmiştir!</i>\n\n⚡ <b>BOTUN 7/24 SÜRESİZ VE KESİNTİSİZ ÇALIŞMASI İÇİN:</b>\n\nRender ücretsiz planları 15 dakika istek almadığında uyku moduna geçer. Botunuzun <b>hiç uyumaması ve 7/24 kesintisiz çalışması için</b> aşağıdaki 2 resimli UptimeRobot adımını tamamlayın:\n\n",
        "deploy_error": "❌ Render Deploy Hatası:\n`{e}`\n\nYeniden başlamak veya botu kaldırmak isterseniz aşağıdaki butonları kullanabilirsiniz:",
        "uptime_step_1_cap": "📸 <b>UptimeRobot - 1. Adım:</b>\n1️⃣ uptimerobot.com sitesine üye olun ve giriş yapın.\n2️⃣ <b>Add New Monitor</b> (Yeni Monitör Ekle) butonuna tıklayın.\n3️⃣ Monitor Type olarak <b>HTTP(s)</b> seçin.\n4️⃣ İsim olarak <b>GagaraGogo</b> veya istediğiniz bir şey yazın.\nURL kutusuna botun size verdiği canlı linkin tamamını yapıştırın:\n<code>{app_live_url}</code>",
        "uptime_step_2_cap": "📸 <b>UptimeRobot - 2. Adım:</b>\nDaire içindeki <b>+ New</b> butonunun yanındaki oka basarak açılan menüden <b>Single monitor</b> seçeneğine tıklayın. Ardından en alttaki <b>Create monitor</b> butonuna basın. Başka hiçbir şey yapmanıza gerek yoktur, botunuz 7/24 aktif kalacaktır!",
        "timeout_title": "⏳ <b>Süre Doldu!</b>\n",
        "timeout_msg": "Yarım kalan işlem ve sohbetteki tüm önceki mesajlar güvenliğiniz için kalıcı olarak silinmiştir.\n\nYeniden başlamak veya botu kaldırmak isterseniz aşağıdaki butonları kullanabilirsiniz:",
        "cleaning_up": "Güvenliğiniz için yarım kalan işlem ve sohbet geçmişi temizleniyor...",
        "clean_complete_title": "🔒 <b>Güvenlik Temizliği Tamamlandı!</b>\n\n",
        "clean_complete_msg": "Önceki tüm kurulum mesajları, hassas anahtarlarınız ve sohbet geçmişiniz gizliliğiniz için kalıcı olarak silinmiştir.\n\nYeniden başlamak veya botu kaldırmak isterseniz aşağıdaki butonları kullanabilirsiniz:",
        "clean_success_msg": "✅ <b>Botunuz 7/24 kesintisiz çalışmaya devam etmektedir.</b>\n"
    },
    "en": {
        "lang_selection": "👋 <b>Hello {first_name}!</b>\n\n🤖 <b>GagaraGogo Userbot Setup Assistant</b>\nPlease select your preferred language:",
        "start_en_btn": "🇬🇧 English",
        "start_tr_btn": "🇹🇷 Türkçe",
        "start_welcome": "👋 <b>Hello {first_name}!</b>\n\n🤖 Welcome to <b>GagaraGogo Userbot Automated Setup Assistant</b>.\n\nWith this assistant, without writing a single line of code:\n1️⃣ Connect your Render account,\n2️⃣ Retrieve API ID and HASH from <code>my.telegram.org</code>,\n3️⃣ Generate your Pyrogram String Session,\n4️⃣ Create an assistant bot automatically via <code>@BotFather</code>,\n5️⃣ Deploy your userbot to Render with a 24/7 Uptime monitor!\n\n🔒 <b>Security & Zero Storage:</b>\n<i>Your phone numbers, passwords, and sessions are NEVER stored.</i>\n\n⏳ <b>Privacy Protection:</b>\n• Completed setups: <b>After 5 minutes</b>\n• Cancelled or idle setups: <b>After 30 minutes</b>\nall messages in this chat will be completely and automatically wiped!\n\n⚠️ <b>Disclaimer:</b>\n<i>Userbots carry potential risks under Telegram Terms of Service. You are solely responsible for your account actions. By proceeding, you agree to these terms.</i>\n\n📁 <b>Source Code:</b>\n<a href='https://github.com/chaolcam/gagaragogo-kurulum-bot'>github.com/chaolcam/gagaragogo-kurulum-bot</a>",
        "btn_start_setup": "🚀 Start Setup",
        "btn_remove_bot": "🗑️ Remove Bot from Account",
        "btn_lang_change": "🌐 Dil / Language (TR / EN)",
        "btn_privacy": "ℹ️ Privacy & Security",
        "btn_github": "📁 GitHub Repository",
        "render_step_1_cap": "📸 <b>Render - Step 1:</b>\nClick on your profile icon at the top right, then select <b>Account settings</b> from the menu.",
        "render_step_2_cap": "📸 <b>Render - Step 2:</b>\nGo to the <b>API Keys</b> tab on the left menu and click the <b>Create API Key</b> button. Name it and confirm. Copy the API key starting with <code>rnd_...</code>.",
        "step_1_render_key": "🌐 <b>Step 1: Render API Key</b>\n\nTo connect the server where your bot will run 24/7 for free, your Render API key is required:\n\n1️⃣ Go to <a href='https://dashboard.render.com/'>dashboard.render.com</a> and log in.\n2️⃣ Create your <code>rnd_...</code> key as shown in the pictures above.\n3️⃣ Copy and paste the generated <code>rnd_...</code> key here:\n\n❌ <i>Type /cancel to cancel.</i>",
        "remove_bot_msg": "🗑️ <b>Removing GagaraGogo Userbot</b>\n\nPlease send your **Render API Key** (`rnd_...`) to delete the service from your Render account:",
        "privacy_info": "🛡️ <b>GagaraGogo Security & Privacy Principles</b>\n\n• <b>100% Open Source:</b>\nAll setup and deployment source codes are public on GitHub:\n👉 <a href='https://github.com/chaolcam/gagaragogo-kurulum-bot'>github.com/chaolcam/gagaragogo-kurulum-bot</a>\n\n• <b>Zero-Persistence:</b>\nAPI keys, phone numbers, or verification codes are <b>never</b> saved to a database or disk. They are processed in temporary RAM and destroyed immediately after.\n\n• <b>Automated Chat Wipe:</b>\n1️⃣ Successful setups: <b>After 5 minutes</b>\n2️⃣ Cancelled/incomplete processes: <b>After 30 minutes</b>\nAll sensitive messages in this chat are automatically and completely deleted for your security.\n\n• <b>⚠️ Disclaimer:</b>\nUsing a userbot is a third-party modification and your Telegram account may be limited or banned. This is an open-source project; you are <b>solely responsible</b> for your account and actions. GagaraGogo developers accept no responsibility.",
        "btn_back_main": "⬅️ Return to Main Menu",
        "wait_botfather": "⏳ <i>Talking to @BotFather, opening your assistant bot and inline menu...</i>",
        "auto_bot_error": "⚠️ An error occurred during automatic bot creation: `{e}`\n\nPlease send a Bot Token manually retrieved from @BotFather:",
        "manual_bot_msg": "✏️ Please paste your bot token from @BotFather:\nExample: `1234567890:ABCdef...`",
        "official_api_selected": "✅ <b>Official Telegram Android API Selected!</b>\n• API ID: <code>2040</code>\n• API HASH: <code>b18441a1ff607e10a989891a5462e627</code>\n\n⏳ <i>Sending your login verification code (SMS/Telegram)...</i>",
        "retry_code": "⏳ <i>Requesting login code again...</i>",
        "start_command_required": "Please use the /start command to begin the setup.",
        "invalid_render_key": "⚠️ Render API keys start with `rnd_`. Please make sure you entered the correct key:",
        "verifying_render_key": "⏳ <i>Verifying Render API key...</i>",
        "render_key_success": "✅ <b>Render API Key Verified!</b>\n\n📱 <b>Step 2: Telegram Phone Number</b>\n\nShare your phone number via the button below or type it in international format:\nExample: `+905551234567`\n\n🔒 <i>Your number is ONLY used to request an instant Telegram verification code, and is NEVER saved.</i>",
        "render_key_error": "❌ <b>Error:</b> {e}\n\nPlease check your Render API key and send it again:",
        "btn_share_phone": "📱 Share My Phone Number",
        "invalid_phone": "❌ Invalid phone number. Please enter in the format: `+905551234567`:",
        "contacting_my_tg": "⏳ Contacting <b>my.telegram.org</b>...\nNumber: <code>{phone}</code>",
        "tg_code_sent": "📨 <b>Telegram Verification Code Sent!</b>\n\nEnter the web login code you received from official Telegram notifications.\n\n⚠️ <b>IMPORTANT FORMAT WARNING:</b>\nBecause Telegram blocks automated codes, please enter the code <b>with spaces between the digits</b>:\n👉 <i>Example: If code is <code>93964</code>, enter it as <code>9 3 9 6 4</code> or <code>9.3.9.6.4</code>.</i>\n\n❌ <i>Type /cancel to cancel.</i>",
        "mytg_unreachable": "⚠️ <b>my.telegram.org is Unreachable</b>\n\nThe website is unresponsive due to Telegram server load.\nBut don't worry! You can proceed using the official ready-to-use Telegram Android app API keys:",
        "btn_use_official_api": "✅ Continue with Official Android API",
        "btn_cancel": "❌ Cancel",
        "logging_in_mytg": "⏳ <i>Logging into my.telegram.org and retrieving API keys...</i>",
        "api_retrieved": "✅ <b>API Details Successfully Retrieved!</b>\n\n• <b>API ID:</b> <code>{api_id}</code>\n• <b>API HASH:</b> <code>{api_hash}</code>\n\n⏳ <i>Now sending a login code to your Telegram app to generate a String Session...</i>",
        "generating_session": "⏳ <i>Logging in and generating String Session...</i>",
        "session_code_sent": "📱 <b>Telegram Login Code Sent!</b>\n\nPlease send the login code received in your Telegram app here.\n\n⚠️ <b>IMPORTANT:</b> Type the code <b>with spaces</b>:\n👉 <i>Example: <code>1 2 3 4 5</code></i>",
        "session_code_error": "❌ Error sending code: `{e}`\n\nPlease try again:",
        "login_error": "❌ <b>Login Error:</b> {e}\n\nPlease make sure you entered the code correctly (Ex: <code>9 3 9 6 4</code>) or try again via /start.",
        "verifying_2fa": "⏳ <i>Verifying 2FA password...</i>",
        "need_2fa": "🔐 <b>Two-Step Verification (2FA) Password Required</b>\n\nYour account has a 2FA password enabled. Please send your Telegram cloud password as a message:\n\n🔒 <i>Your password is never saved anywhere, and is completely wiped from memory after instant verification.</i>",
        "2fa_error": "❌ <b>Error:</b> {e}\n\nPlease try your password again or type /cancel.",
        "session_success": "🔐 <b>String Session Successfully Generated!</b>\n\n🤖 <b>Final Step: Assistant Bot Setup</b>\n\nGagaraGogo Userbot requires an assistant bot for inline button menus and settings panel.\n\n• <b>Auto Create:</b> Your bot talks to @BotFather and instantly creates a new bot and sets up inline mode.\n• <b>Manual Entry:</b> You can paste a Bot Token you obtained previously.\n\nChoose whether to open the assistant bot automatically or enter manually.",
        "btn_auto_bot": "🤖 Auto Create Bot (Recommended)",
        "btn_manual_bot": "✏️ I'll Enter Bot Token Manually",
        "invalid_bot_token": "❌ Invalid bot token format! Ex: `1234567890:ABCdef...`",
        "searching_render_service": "⏳ <i>Searching for 'gagaragogo-userbot' service on your Render account and deleting it...</i>",
        "no_render_service": "ℹ️ No active 'gagaragogo-userbot' service found on your Render account.\nYou can use the buttons below to start over or remove the bot:",
        "remove_success": "✅ <b>Your GagaraGogo Userbot Render service has been successfully deleted!</b>\n\nAll server operations and resources have been completely removed from your account.\nYou can use the buttons below to start over or remove the bot:",
        "remove_error": "❌ Removal Error: {e}\nYou can use the buttons below to start over or remove the bot:",
        "btn_restart_setup": "🚀 Start Setup Again",
        "cancel_full": "❌ <b>Operation cancelled.</b>\n\nAll temporary data has been wiped from memory.\n⏳ <i>For your security, this chat will be automatically cleaned in 30 minutes.</i>",
        "deploy_starting": "🚀 <b>GagaraGogo Setup Starting...</b>\n\nCreating the <code>gagaragogo-userbot</code> service on your Render account and injecting variables...",
        "deploy_success": "🎉 <b>CONGRATULATIONS! GAGARAGOGO USERBOT IS DEPLOYED!</b>\n\n🚀 <b>Your Render Web Service has Started:</b>\n• <b>Service Name:</b> <code>{name}</code>\n• <b>Dashboard Link:</b> <a href='{dashboard_url}'>Render Dashboard</a>\n\n🔗 <b>Your Exclusive Live Web Address:</b>\n👉 <code>{app_live_url}</code>\n\n🔑 <b>Your Account Keys:</b>\n<i>(Your setup and access information are stored in your Telegram Saved Messages chat.)</i>\n\n<i>For your security, all setup messages and keys in this chat will be <b>automatically deleted in 5 minutes</b>. Your setup information is safely backed up to your Saved Messages!</i>\n\n⚡ <b>TO KEEP THE BOT RUNNING 24/7 WITHOUT INTERRUPTION:</b>\n\nRender free plans go to sleep when they don't receive requests for 15 minutes. <b>To ensure your bot never sleeps and runs 24/7</b>, complete the 2 UptimeRobot steps illustrated below:\n\n",
        "deploy_error": "❌ Render Deploy Error:\n`{e}`\n\nYou can use the buttons below to start over or remove the bot:",
        "uptime_step_1_cap": "📸 <b>UptimeRobot - Step 1:</b>\n1️⃣ Sign up and log in to uptimerobot.com.\n2️⃣ Click the <b>Add New Monitor</b> button.\n3️⃣ Select <b>HTTP(s)</b> as the Monitor Type.\n4️⃣ Enter <b>GagaraGogo</b> or anything you want as the name.\nPaste the entire live link provided by the bot into the URL box:\n<code>{app_live_url}</code>",
        "uptime_step_2_cap": "📸 <b>UptimeRobot - Step 2:</b>\nClick the arrow next to the circled <b>+ New</b> button and select <b>Single monitor</b> from the dropdown menu. Then click the <b>Create monitor</b> button at the bottom. You don't need to do anything else, your bot will stay active 24/7!",
        "timeout_title": "⏳ <b>Time is Up!</b>\n",
        "timeout_msg": "Incomplete processes and all previous messages in the chat have been permanently deleted for your security.\n\nYou can use the buttons below to start over or remove the bot:",
        "cleaning_up": "Cleaning up incomplete processes and chat history for your security...",
        "clean_complete_title": "🔒 <b>Security Cleanup Complete!</b>\n\n",
        "clean_complete_msg": "All previous setup messages, your sensitive keys, and chat history have been permanently deleted for your privacy.\n\nYou can use the buttons below to start over or remove the bot:",
        "clean_success_msg": "✅ <b>Your bot continues to run 24/7 without interruption.</b>\n"
    }
}

def get_text(lang: str, key: str, **kwargs) -> str:
    if lang not in MESSAGES:
        lang = "tr"
    text = MESSAGES[lang].get(key)
    if text is None:
        return f"[{key}]"
    if kwargs:
        return text.format(**kwargs)
    return text
